# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created: Thu Feb 16 18:40:08 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(250, 500)
        MainWindow.setMinimumSize(QtCore.QSize(250, 500))
        MainWindow.setMaximumSize(QtCore.QSize(250, 500))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 251, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.space = QtGui.QLabel(self.verticalLayoutWidget)
        self.space.setObjectName("space")
        self.horizontalLayout_4.addWidget(self.space)
        self.spaceBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.spaceBox.setObjectName("spaceBox")
        self.spaceBox.addItem("")
        self.spaceBox.addItem("")
        self.horizontalLayout_4.addWidget(self.spaceBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.space_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.space_2.setObjectName("space_2")
        self.horizontalLayout_5.addWidget(self.space_2)
        self.axisBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.axisBox.setObjectName("axisBox")
        self.axisBox.addItem("")
        self.axisBox.addItem("")
        self.axisBox.addItem("")
        self.horizontalLayout_5.addWidget(self.axisBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.tolleranceLine = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.tolleranceLine.setMaximumSize(QtCore.QSize(50, 16777215))
        self.tolleranceLine.setObjectName("tolleranceLine")
        self.horizontalLayout.addWidget(self.tolleranceLine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.baseObjectButton = QtGui.QToolButton(self.verticalLayoutWidget)
        self.baseObjectButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        icon = QtGui.QIcon(":/navButtonConnected.png")
        self.baseObjectButton.setIcon(icon)
        self.baseObjectButton.setObjectName("baseObjectButton")
        self.horizontalLayout_3.addWidget(self.baseObjectButton)
        self.baseObjectText = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.baseObjectText.setObjectName("baseObjectText")
        self.horizontalLayout_3.addWidget(self.baseObjectText)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.mapVerticesButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.mapVerticesButton.setObjectName("mapVerticesButton")
        self.verticalLayout.addWidget(self.mapVerticesButton)
        spacerItem1 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_3.setMargin(4)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.checkSymmetryButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.checkSymmetryButton.setObjectName("checkSymmetryButton")
        self.verticalLayout.addWidget(self.checkSymmetryButton)
        self.symmetricalMeshButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.symmetricalMeshButton.setObjectName("symmetricalMeshButton")
        self.verticalLayout.addWidget(self.symmetricalMeshButton)
        spacerItem2 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setMargin(4)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.flipSelectionButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.flipSelectionButton.setObjectName("flipSelectionButton")
        self.verticalLayout.addWidget(self.flipSelectionButton)
        self.mirrorSelectionLRButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.mirrorSelectionLRButton.setObjectName("mirrorSelectionLRButton")
        self.verticalLayout.addWidget(self.mirrorSelectionLRButton)
        self.mirrorSelectionRLButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.mirrorSelectionRLButton.setObjectName("mirrorSelectionRLButton")
        self.verticalLayout.addWidget(self.mirrorSelectionRLButton)
        spacerItem3 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.revertToBaseButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.revertToBaseButton.setObjectName("revertToBaseButton")
        self.verticalLayout.addWidget(self.revertToBaseButton)
        self.flipMeshButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.flipMeshButton.setObjectName("flipMeshButton")
        self.verticalLayout.addWidget(self.flipMeshButton)
        self.mirrorMeshLRButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.mirrorMeshLRButton.setObjectName("mirrorMeshLRButton")
        self.verticalLayout.addWidget(self.mirrorMeshLRButton)
        self.mirrorMeshRLButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.mirrorMeshRLButton.setObjectName("mirrorMeshRLButton")
        self.verticalLayout.addWidget(self.mirrorMeshRLButton)
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 250, 21))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)
        self.actionDaniele_Dolci = QtGui.QAction(MainWindow)
        self.actionDaniele_Dolci.setCheckable(False)
        self.actionDaniele_Dolci.setChecked(False)
        self.actionDaniele_Dolci.setObjectName("actionDaniele_Dolci")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setCheckable(False)
        self.actionHelp.setChecked(False)
        self.actionHelp.setObjectName("actionHelp")
        self.menu.addAction(self.actionDaniele_Dolci)
        self.menu.addAction(self.actionHelp)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spaceBox, self.axisBox)
        MainWindow.setTabOrder(self.axisBox, self.checkSymmetryButton)
        MainWindow.setTabOrder(self.checkSymmetryButton, self.symmetricalMeshButton)
        MainWindow.setTabOrder(self.symmetricalMeshButton, self.flipSelectionButton)
        MainWindow.setTabOrder(self.flipSelectionButton, self.mirrorSelectionLRButton)
        MainWindow.setTabOrder(self.mirrorSelectionLRButton, self.mirrorSelectionRLButton)
        MainWindow.setTabOrder(self.mirrorSelectionRLButton, self.revertToBaseButton)
        MainWindow.setTabOrder(self.revertToBaseButton, self.flipMeshButton)
        MainWindow.setTabOrder(self.flipMeshButton, self.mirrorMeshLRButton)
        MainWindow.setTabOrder(self.mirrorMeshLRButton, self.mirrorMeshRLButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.space.setText(QtGui.QApplication.translate("MainWindow", "Space:", None, QtGui.QApplication.UnicodeUTF8))
        self.spaceBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Local", None, QtGui.QApplication.UnicodeUTF8))
        self.spaceBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "World", None, QtGui.QApplication.UnicodeUTF8))
        self.space_2.setText(QtGui.QApplication.translate("MainWindow", "Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.axisBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.axisBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.axisBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Tollerance", None, QtGui.QApplication.UnicodeUTF8))
        self.tolleranceLine.setText(QtGui.QApplication.translate("MainWindow", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Base Object: ", None, QtGui.QApplication.UnicodeUTF8))
        self.baseObjectButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.mapVerticesButton.setText(QtGui.QApplication.translate("MainWindow", "Map Vertices", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Utilities Tools:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSymmetryButton.setText(QtGui.QApplication.translate("MainWindow", "Check Symmetry", None, QtGui.QApplication.UnicodeUTF8))
        self.symmetricalMeshButton.setText(QtGui.QApplication.translate("MainWindow", "Create Symmetrical Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Selection Tools:", None, QtGui.QApplication.UnicodeUTF8))
        self.flipSelectionButton.setText(QtGui.QApplication.translate("MainWindow", "Flip Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorSelectionLRButton.setText(QtGui.QApplication.translate("MainWindow", "Mirror Selection  L >> R", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorSelectionRLButton.setText(QtGui.QApplication.translate("MainWindow", "Mirror Selection R >> L", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Deforming Tools:", None, QtGui.QApplication.UnicodeUTF8))
        self.revertToBaseButton.setText(QtGui.QApplication.translate("MainWindow", "Revert Target to Base", None, QtGui.QApplication.UnicodeUTF8))
        self.flipMeshButton.setText(QtGui.QApplication.translate("MainWindow", "Flip mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorMeshLRButton.setText(QtGui.QApplication.translate("MainWindow", "Mirror mesh L >> R", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorMeshRLButton.setText(QtGui.QApplication.translate("MainWindow", "Mirror mesh R >> L", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDaniele_Dolci.setText(QtGui.QApplication.translate("MainWindow", "Daniele Dolci", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

"""
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
"""
